baseURL = "https://quantumdevpro.github.io/"
title = "Student Diary"
theme = "PaperMod"
languageCode = "ar-sa"
defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = false
paginate = 20
buildFuture = true

[languages]
  [languages.ar]
    languageName = "العربية"
    languageDirection = "rtl"
    weight = 1

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

  [params.profileMode]
    enabled = true
    title = "Haneen Alharbi"
    subtitle = "Cybersecurity Bachelor Student | Learning in Public"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/QuantumDevPro"

[menu]
  [[menu.main]]
    name = "Journey"
    url = "/levels/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 20